baseurl = "https://azharkhan.in/"
theme="hc-starter"
languageCode = "en"
title = "Azhar Khan"
pluralizelisttitles = false

# Enable for syntax highlighting
pygmentsUseClasses=true
# Enable highlighting for code fences
pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true

[params]
  keywords = "Data Engineering, Data Science, AI, Analytics, Design, UX, UI, Product"
  description = "Azhar Khan is a professional developer and data engineer from Ottawa, ON. I write articles and notes on Data Engineeering with a little bit of Product Management sprinkled in between."
  strapline = "Data Engineering, Viz & Product Management"
  location = "Ottawa, ON"

  # Set Cloudinary URL for image hosting
  cloudinary_url = "https://res.cloudinary.com/azhar932/image/upload"
  author = "Azhar Khan"

[author]
  name = "Azhar Khan"
  email = "akhan@azharkhan.in"
  twitter = "https://twitter.com/AzharCan"
  github = "https://github.com/XOR97"
  linkedin = "https://www.linkedin.com/in/Azhar93/"

[taxonomies]
  tag = "tags"

[outputs]
  home = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"

[permalinks]
  articles = "/:section/:slug/"
  projects = "/:section/:slug/"
  notes = "/:section/:slug/"
  page = "/:title/"

# Enable Emojis
enableEmoji = true

[[menu.main]]
  name = "Articles"
  url = "/articles/"
  weight = 10

[[menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 15

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 20

[[menu.footer]]
  name = "Articles"
  url = "/articles/"
  weight = 10

[[menu.footer]]
  name = "Notes"
  url = "/notes/"
  weight = 15

[[menu.footer]]
  name = "Tags"
  url = "/tags/"
  weight = 20
